const res = {
  data: [
    {
      goods_classify: 1,
      sale_status: 1,
      plat_goods_id: '611708119793',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i4/1039348337/O1CN01awrkG72BSOaCSMRqI_!!1039348337.png',
      plat_goods_name: '对酒当歌的曹操',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=611708119793',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L11111111111111"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '621661283976',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i1/1039348337/O1CN01U6kJ7R2BSOasrhnl2_!!1039348337.png',
      plat_goods_name: '好穿的啦啦体恤',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=621661283976',
      sku_list: []
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '605880736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 2,
      plat_goods_id: '605880736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '60588071362759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '605880736722159',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 2,
      plat_goods_id: '12323232759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '231231234214123126',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '60582321380736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 1,
      plat_goods_id: '6023235880736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 1,
      plat_goods_id: '60582323180736723359',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '1610225880736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 1,
      plat_goods_id: '60588073675923213',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '60523838073236759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 1,
      plat_goods_id: '60588232307323236759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '6023232355880457232336759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 2,
      plat_goods_id: '605284880736536759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 2,
      plat_goods_id: '6305880232373673359',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 1,
      plat_goods_id: '63058382307323326759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '989767200192',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 1,
      plat_goods_id: '097666555661',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 2,
      plat_goods_id: '98755578644566787',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '097676768781',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 2,
      plat_goods_id: '090908787767554545',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '3232132345677878',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 1,
      plat_goods_id: '542151284718247821',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '560588023736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 1,
      plat_goods_id: '36058231280736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 1,
      plat_goods_id: '60588072222222222136759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 2,
      plat_goods_id: '605880732113123126759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 2,
      plat_goods_id: '1233131231221111111111',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '1111111111111111',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 1,
      plat_goods_id: '3322222222222222222223',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 1,
      sale_status: 2,
      plat_goods_id: '6058232138230736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 2,
      sale_status: 2,
      plat_goods_id: '213124535235234',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 1,
      plat_goods_id: '23213123124523',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }, {
      goods_classify: 3,
      sale_status: 2,
      plat_goods_id: '6076765465884560736759',
      plat_goods_img:
        'https://img.alicdn.com/bao/uploaded/i2/1039348337/O1CN01rNn0EZ2BSOZ8Tt1US_!!1039348337.jpg',
      plat_goods_name: '自用手机轻便得很',
      plat_goods_url: 'https://item.taobao.com/item.htm?id=605880736759',
      sku_list: [{
        sku_id: 1,
        sku_props_name: "这是商品SKU的名称-L"
      }, {
        sku_id: 2,
        sku_props_name: "这是商品SKU的名称-XL"
      }, {
        sku_id: 3,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 4,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 5,
        sku_props_name: "这是商品SKU的名称-XS"
      }, {
        sku_id: 6,
        sku_props_name: "这是商品S111"
      }, {
        sku_id: 7,
        sku_props_name: "这是商品S11"
      }, {
        sku_id: 8,
        sku_props_name: "这是商品SK1"
      }, {
        sku_id: 9,
        sku_props_name: "这是商品S1"
      }, {
        sku_id: 10,
        sku_props_name: "这是商品SK"
      }, {
        sku_id: 11,
        sku_props_name: "这是商品S"
      }]
    }
  ]
}
res.total = res.data.length

module.exports = res

